USE [ejdevo]
GO
/****** Object:  StoredProcedure [dbo].[USP_DATALIST_ADHOCQUERY_67A7A9F1_826B_46CA_A74F_24E6A1E46E87]    Script Date: 13-Sep-19 4:59:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER procedure [dbo].[USP_DATALIST_ADHOCQUERY_67A7A9F1_826B_46CA_A74F_24E6A1E46E87](
@OWNER nvarchar(154) = null,
	@CURRENTAPPUSERID uniqueidentifier,
	@SECURITYFEATUREID uniqueidentifier,
	@SECURITYFEATURETYPE tinyint,
	@MAXROWS int = 100000) as
set nocount on;
set @OWNER = dbo.UFN_SEARCHCRITERIA_GETLIKEPARAMETERVALUE2(@OWNER, 0, null, 0);
with
[ROOT_CTE] as (
SELECT
C.NAME
,C.LookupID as [Lookup ID]
,PP.Name as [Plan]
,I.CONTACTMETHOD as [Contact Method]
,I.OBJECTIVE as [Summary]
,I.CATEGORY_TRANSLATION as [Category]
,I.EXPECTEDDATE as [Expected Date]
,O.Name as [Owner]
,I.Comment as [Comment]
,O.ID as [Owner Record ID]
,C.CONSTITUENTID as [Constituent Record ID]
,OTEAM.BUSINESSUNIT as [Team]
,case when [I].[PROSPECTPLANID] is not null then 'True'
else 'False' end as [Ismove]
,I.ID as [Interaction Record ID]
,PP.ID as [Plan ID]
FROM V_QUERY_INTERACTIONALL I 
LEFT JOIN V_QUERY_PROSPECTPLAN as PP on I.PROSPECTPLANID = PP.ID
LEFT OUTER JOIN V_QUERY_CONSTITUENT [O] ON [O].ID = I.OWNERID
LEFT OUTER JOIN (
	SELECT
		[CONSTITUENT].[ID] [CONSTITUENTID],
		[DBO].[UFN_BUSINESSUNITCODE_GETDESCRIPTION](ORGANIZATIONPOSITION.BUSINESSUNITCODEID) [BUSINESSUNIT]
	FROM [DBO].[ORGANIZATIONHIERARCHY]
	INNER JOIN DBO.ORGANIZATIONPOSITION ON ORGANIZATIONPOSITION.ID = ORGANIZATIONHIERARCHY.ID
	LEFT OUTER JOIN DBO.ORGANIZATIONPOSITIONHOLDER ON ORGANIZATIONPOSITIONHOLDER.POSITIONID = ORGANIZATIONPOSITION.ID
	LEFT OUTER JOIN DBO.CONSTITUENT ON CONSTITUENT.ID = ORGANIZATIONPOSITIONHOLDER.CONSTITUENTID
	WHERE ORGANIZATIONPOSITIONHOLDER.DATETO IS NULL
	) [OTEAM] ON O.[ID] = OTEAM.[CONSTITUENTID]

LEFT OUTER JOIN EJ_CONSTITUENT_HISTORY as C on [C].[CONSTITUENTID] = I.CONSTITUENTID
LEFT OUTER JOIN V_QUERY_ADDRESSEE_SALUTATION as [ADDSAL] on [C].[CONSTITUENTID] = [ADDSAL].[ID]
LEFT OUTER JOIN dbo.[UFN_ADHOCQUERYIDSET_F524CA2C_5E71_47ED_9049_71C79D1226F7]() as [Do Not Contact] on [C].[CONSTITUENTID] = [Do Not Contact].ID
LEFT OUTER JOIN dbo.[UFN_ADHOCQUERYIDSET_71B9837E_32F7_4D66_BBAC_53A36F3731F9]() as [Do Not Call] on [C].[CONSTITUENTID] = [Do Not Call].ID
LEFT OUTER JOIN dbo.[UFN_ADHOCQUERYIDSET_8367E7CC_AEA4_4C6A_B9D0_3CC48D753C9D]() as [Do Not Email] on [C].[CONSTITUENTID] = [Do Not Email].ID

WHERE I.STATUS in ('Pending','Planned')
AND CONTACTMETHOD in ('Report', 'Proposal')
AND C.DECEASED = 0 and C.INACTIVE = 0 
AND [Do Not Contact].ID is null
AND OTEAM.BUSINESSUNIT = 'Foundations'
)


select top(@MAXROWS) [Name],
	[Lookup ID],
	[Plan],
	[Contact method],
	[Summary],
	[Category],
	[Expected date],
	[Owner],
	[Comment],
	[Owner Record ID],
	[Constituent Record ID],
	[Team],
	[Ismove],
	[Interaction Record ID],
	[Plan ID]
from [ROOT_CTE] as QUERYRESULTS
where ((@OWNER is null or @OWNER = '') or QUERYRESULTS.[Owner] LIKE  '%' + @OWNER + '%')

order by [Name] asc, [Expected date] asc
