SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

UPDATE EJ_PROSPECT_PIPELINE_STATUS
set EVENTID = SUB.EVENTID,
	LASTEVENT = SUB.EVENTNAME,
	UPCOMINGMOVES = SUB.NEXTMOVES 

from
(
select distinct
	PIPELINE.PROSPECTID,
	PRIOR_EVENT.NAME [EVENTNAME],
	PRIOR_EVENT.EVENTID [EVENTID],
	PLANNED_MOVES.NEXTMOVES
from
EJ_PROSPECT_PIPELINE_STATUS PIPELINE

left outer join (
							
							select distinct
							
									PREVIOUS_EVENTDATE.CONSTITUENTID,
									PREVIOUS_EVENTDATE.STARTDATE STARTDATE, 
									PREVIOUS_EVENTDATE.NAME NAME,
									PREVIOUS_EVENTDATE.ID EVENTID
								from  	
								 (
										select distinct
											REGISTRANT.CONSTITUENTID CONSTITUENTID,
											EVENT.STARTDATE STARTDATE,
											EVENT.NAME, 
											EVENT.ID,
											ROW_NUMBER() OVER (PARTITION BY REGISTRANT.CONSTITUENTID
															 ORDER BY REGISTRANT.CONSTITUENTID,
															EVENT.STARTDATE desc) AS ROWNUMBER

										from  [dbo].[V_QUERY_CONSTITUENTREGISTRANT] as REGISTRANT
										left outer join [dbo].[V_QUERY_EVENT] as EVENT on REGISTRANT.[EVENTID] = EVENT.ID
										where EVENT.STARTDATE < getDate()
									) PREVIOUS_EVENTDATE
								where PREVIOUS_EVENTDATE.ROWNUMBER = 1					
				) PRIOR_EVENT on PRIOR_EVENT.CONSTITUENTID = PIPELINE.PROSPECTID

left outer join (
				select distinct
					TEMP2.CONSTITUENTID,
					NEXTMOVES = stuff((
										select 
											'; ' + 
											MOVE 
										from (
												select
													SUB.CONSTITUENTID,
													concat(SUB.SUBCATEGORY, ' - ', SUB.DATE, ' - ', SUB.OBJECTIVE) MOVE
												from (
													select
														INTERACTION.CONSTITUENTID,
														INTERACTION.ID INTERACTION,
														convert(char(10), INTERACTION.DATE, 101) DATE,
														INTERACTION.STATUS,
														INTERACTIONSUBCATEGORY.NAME SUBCATEGORY,
														INTERACTIONTYPECODE.DESCRIPTION CONTACT_METHOD,
														INTERACTION.OBJECTIVE,
														INTERACTION.PROSPECTPLANSTEPSTAGE CATEGORY,
														ROW_NUMBER() OVER (PARTITION BY INTERACTION.CONSTITUENTID
																						ORDER BY INTERACTION.CONSTITUENTID,
																					INTERACTION.DATE asc) AS ROWNUMBER
													from V_QUERY_INTERACTIONALL INTERACTION
													inner join INTERACTIONSUBCATEGORY on INTERACTION.INTERACTIONSUBCATEGORYID = INTERACTIONSUBCATEGORY.ID
													inner join INTERACTIONTYPECODE on INTERACTION.INTERACTIONTYPECODEID = INTERACTIONTYPECODE.ID
													where INTERACTION.DATE > dateadd(month, -3, getDate())
														and INTERACTION.COMPLETED = 0
														--and INTERACTION.PROSPECTPLANID is not null
													 ) SUB
												where SUB.ROWNUMBER <= 4
											) TEMP1
											where TEMP1.CONSTITUENTID = TEMP2.CONSTITUENTID
											for xml path ('')), 1, 1, '')
				from (
						select distinct
							SUB.CONSTITUENTID,
							concat(SUB.SUBCATEGORY, ' - ', SUB.DATE, ' - ', SUB.OBJECTIVE) MOVE
						from (
							select
								INTERACTION.CONSTITUENTID,
								INTERACTION.ID INTERACTION,
								convert(char(10), INTERACTION.DATE, 101) DATE,
								INTERACTION.STATUS,
								INTERACTIONSUBCATEGORY.NAME SUBCATEGORY,
								INTERACTIONTYPECODE.DESCRIPTION CONTACT_METHOD,
								INTERACTION.OBJECTIVE,
								INTERACTION.PROSPECTPLANSTEPSTAGE CATEGORY,
								ROW_NUMBER() OVER (PARTITION BY INTERACTION.CONSTITUENTID
															 ORDER BY INTERACTION.CONSTITUENTID,
															INTERACTION.DATE asc) AS ROWNUMBER
							from V_QUERY_INTERACTIONALL INTERACTION
							inner join INTERACTIONSUBCATEGORY on INTERACTION.INTERACTIONSUBCATEGORYID = INTERACTIONSUBCATEGORY.ID
							inner join INTERACTIONTYPECODE on INTERACTION.INTERACTIONTYPECODEID = INTERACTIONTYPECODE.ID
							where INTERACTION.DATE >= dateadd(month, -3, getDate())
								and INTERACTION.COMPLETED = 0
								--and INTERACTION.PROSPECTPLANID is not null
							) SUB
						where SUB.ROWNUMBER <= 4
					) TEMP2
				) PLANNED_MOVES on PIPELINE.PROSPECTID = PLANNED_MOVES.CONSTITUENTID

) SUB
where EJ_PROSPECT_PIPELINE_STATUS.PROSPECTID = SUB.PROSPECTID