use EJDEVO

SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
delete from EJ_CONSTITUENT;

INSERT INTO EJ_CONSTITUENT (CONSTITUENTID, SORT_NAME, LOOKUPID, NAME, AGE, DECEASED, INACTIVE, PRIMARY_CONSTITUENCY, PG,
							PHONE, EMAIL, ADDRESS, CITY, STATE, ZIP, SPOUSE, CHILDREN, GRANDCHILDREN, PROSPECT_MANAGER, 
							PROSPECTSTATUS, AMICUS, PROSPECTPOOL, GENDER, MARITALSTATUS, SPOUSE_CONSTITUENTID, ETHNICITY, DISTINCTYEARGIVING, LATITUDE, LONGITUDE, 
							PROSPECT_MANAGER_TEAM, PROSPECT_MANAGER_USERNAME) 
	SELECT CONSTITUENTID, SORT_NAME, LOOKUPID, NAME, AGE, DECEASED, INACTIVE, PRIMARY_CONSTITUENCY, PG,
			PHONE, EMAIL, ADDRESS, CITY, STATE, ZIP, SPOUSE, CHILDREN, GRANDCHILDREN, PROSPECT_MANAGER, 
			PROSPECTSTATUS, AMICUS, PROSPECTPOOL, GENDER, MARITALSTATUS, SPOUSE_CONSTITUENTID, ETHNICITY, DISTINCTYEARGIVING, LATITUDE, LONGITUDE, 
			PROSPECT_MANAGER_TEAM, PROSPECT_MANAGER_USERNAME
	FROM 
	(	select 
		 [C].[ID] [CONSTITUENTID],
		 [C].[KEYNAME] [SORT_NAME],
		 [C].[LOOKUPID] [LOOKUPID],
		 [C].[NAME] [NAME],
		 case when [C].[AGE] >= 18 and [C].[AGE] <= 100 then [C].[AGE] end [AGE],
		 [C].[DECEASED] [DECEASED],
		 [C].[ISINACTIVE] [INACTIVE],
		 case when [Y].[CONSTITUENCY] = N'Board' then [Y].[CONSTITUENCY]
			  when [Y].[CONSTITUENCY] = N'Council' then [Y].[CONSTITUENCY]
			  when [Y].[CONSTITUENCY] = N'Life Trustee' then [Y].[CONSTITUENCY]
			  when [Y].[CONSTITUENCY] = N'MG' then [Y].[CONSTITUENCY]
			  when [Y].[CONSTITUENCY] = N'FN' then [Y].[CONSTITUENCY]
			  when [Y].[CONSTITUENCY] = N'IG' then [Y].[CONSTITUENCY]
			  when [Y].[CONSTITUENCY] = N'PS' then [Y].[CONSTITUENCY]
			  when [Y].[CONSTITUENCY] = N'FN' then [Y].[CONSTITUENCY]
		 end PRIMARY_CONSTITUENCY,
		 case when [PG].[CONSTITUENCY] = N'PG' then 1
		 end [PG],
		 [P].[NUMBER] [PHONE],
		 [E].[Email Address] [EMAIL],
		 [A].[ADDRESSBLOCK] [ADDRESS],
		 [A].[CITY] [CITY],
		 [A].[STATEID_ABBREVIATION] [STATE],
		 [A].[POSTCODE] [ZIP],
		 [SPOUSE].[NAME] [SPOUSE],
		 [CHILDREN].[VALUE] [CHILDREN],
		 [GRANDCHILDREN].[VALUE] [GRANDCHILDREN],
		 [PM].[PROSPECT_MANAGER] [PROSPECT_MANAGER],
		 [PM].[PROSPECTSTATUSCODE] [PROSPECTSTATUS],
		 case when [AMICUS].[VALUE] is not null then 1 else 0 end [AMICUS],
		 [POOL].[VALUE] [PROSPECTPOOL],
		 [C].GENDER [GENDER],
		 [C].MARITALSTATUSCODEID_TRANSLATION [MARITALSTATUS],
		 [SPOUSE].ID [SPOUSE_CONSTITUENTID],
		 [ETHNICITY].VALUE [ETHNICITY],
		 [DISTINCTYEARSGIVING].VALUE [DISTINCTYEARGIVING],
		 [ADDRESSCOORDINATES].[LATITUDE],
		 [ADDRESSCOORDINATES].[LONGITUDE],
		 [PM].BUSINESSUNIT PROSPECT_MANAGER_TEAM,
		 [PM].USERNAME PROSPECT_MANAGER_USERNAME,
		 [PM].[PROSPECTMANAGERID] [PROSPECTMANAGERID]
		from [V_QUERY_CONSTITUENT] [C]
		left outer join [dbo].[V_QUERY_CONSTITUENTPRIMARYADDRESS] as [A] on [C].[ID] = [A].[CONSTITUENTID]
		left outer join [dbo].[V_QUERY_ADDRESSCOORDINATES] as [ADDRESSCOORDINATES] on [A].ID = ADDRESSCOORDINATES.ADDRESSID
		left outer join [dbo].[USR_V_QUERY_PRIMARYEMAIL] as [E] on [C].[ID] = [E].[CONSTITUENT ID]
		left outer join [dbo].[USR_V_QUERY_PRIMARYPHONE] as [P] on [C].[ID] = [P].[CONSTITUENT ID]
		left outer join [dbo].[V_QUERY_ATTRIBUTE756C044827D14CA4AC63E0B24A65C916] as [CHILDREN] on [C].[ID] = [CHILDREN].[ID]
		left outer join [dbo].[V_QUERY_ATTRIBUTEF2D50120F3E64FCF9166567424ECD657] as [GRANDCHILDREN] on [C].[ID] = [GRANDCHILDREN].[ID]
		left outer join [dbo].[V_QUERY_CONSTITUENT] as [SPOUSE] on [C].[SPOUSE_ID] = [SPOUSE].[ID]
		left outer join [dbo].[V_QUERY_ATTRIBUTED96AC4765DC9466A89567A599B356301] as [ETHNICITY] on [C].[ID] = [ETHNICITY].[ID]
		left outer join [dbo].[V_QUERY_SMARTFIELDBAF5B52C98BA40769C9BB9C890113401] as [DISTINCTYEARSGIVING] on [C].[ID] = [DISTINCTYEARSGIVING].[ID]
		left outer join 
						(select
						  [C].[ID] as [CONSTITUENTID],
						  min([Y].[CONSTITUENCY]) as [CONSTITUENCY]
						 from [V_QUERY_CONSTITUENT] as [C]
						 left outer join [V_QUERY_CONSTITUENCY] as [Y] on [C].[ID] = [Y].[CONSTITUENTID]
						 where ([Y].[CONSTITUENCY] in (N'IG', N'MG', N'Life Trustee', N'Council', N'PS', N'FN', N'Board')
						  and ([Y].[DATETO] is null))
						 group by [C].[ID]
						) [Y] on [C].[ID] = [Y].[CONSTITUENTID]
		left outer join 
						(select [CY].[CONSTITUENTID] [CONSTITUENTID], max([CY].[CONSTITUENCY]) [CONSTITUENCY]
						 from [V_QUERY_CONSTITUENCY] [CY] 
						 where ([CY].[CONSTITUENCY] = ('PG')
						  and ([CY].[DATETO] is null or [CY].[DATETO] <> '' or [CY].[DATETO] = null))
						  group by [CY].[CONSTITUENTID]
						) [PG] on [C].[ID] = [PG].[CONSTITUENTID]
		left outer join
						(select 
						  [P].[ID] [CONSTITUENTID], 
						  max([F].[NAME]) [PROSPECT_MANAGER], 
						  [PROSPECTSTATUSCODE],
						  [dbo].[UFN_BUSINESSUNITCODE_GETDESCRIPTION](ORGANIZATIONPOSITION.BUSINESSUNITCODEID) [BUSINESSUNIT],
						  case when right(APPUSER.USERNAME, len(APPUSER.USERNAME) - charindex('\', APPUSER.USERNAME)) is not null
							   then concat(right(APPUSER.USERNAME, len(APPUSER.USERNAME) - charindex('\', APPUSER.USERNAME)), '@earthjustice.org') 
							   else null
						  end USERNAME,
						  [F].[ID] PROSPECTMANAGERID
						 from [dbo].[V_QUERY_PROSPECT] [P]
						 left outer join [dbo].[V_QUERY_FUNDRAISER] [F] on [P].[PROSPECTMANAGERFUNDRAISERID] = [F].[ID]
						 left outer join dbo.ORGANIZATIONPOSITIONHOLDER on ORGANIZATIONPOSITIONHOLDER.CONSTITUENTID = [F].ID
						 left outer join dbo.ORGANIZATIONPOSITION on ORGANIZATIONPOSITION.ID = ORGANIZATIONPOSITIONHOLDER.POSITIONID
						 left outer join dbo.APPUSER on [F].ID = APPUSER.CONSTITUENTID
						 group by 
							[P].[ID], 
							[P].[PROSPECTSTATUSCODE], 
							[dbo].[UFN_BUSINESSUNITCODE_GETDESCRIPTION](ORGANIZATIONPOSITION.BUSINESSUNITCODEID) ,
							case when right(APPUSER.USERNAME, len(APPUSER.USERNAME) - charindex('\', APPUSER.USERNAME)) is not null
							     then concat(right(APPUSER.USERNAME, len(APPUSER.USERNAME) - charindex('\', APPUSER.USERNAME)), '@earthjustice.org') 
							     else null
						    end,
							[F].[ID]
						) [PM] on [C].[ID] = [PM].[CONSTITUENTID]
		left outer join [dbo].[V_QUERY_ATTRIBUTEFBEF3005372444E88030BC5D22DC24E1]  [AMICUS] on [C].[ID] = [AMICUS].[PARENTID]
						and [AMICUS].[VALUE] = N'Amicus Society'
		left outer join 
						(select 
							PARENTID,  
							[VALUE] = STUFF(
										(select '; ' + [VALUE] 
										 from [dbo].[V_QUERY_ATTRIBUTE14A7B597D42B4BF3B3A2964CD2E1A6BD] ATTR
										 where ATTR.PARENTID = ATTR2.PARENTID
										 for XML PATH (''))
										, 1, 1, '') 
						from [dbo].[V_QUERY_ATTRIBUTE14A7B597D42B4BF3B3A2964CD2E1A6BD] ATTR2
						group by PARENTID
						) [POOL] on [C].[ID] = [POOL].[PARENTID]
	) SUB
	
	group by CONSTITUENTID, SORT_NAME, LOOKUPID, NAME, AGE, DECEASED, INACTIVE, PRIMARY_CONSTITUENCY, PG,
			  PHONE, EMAIL, ADDRESS, CITY, STATE, ZIP, SPOUSE, CHILDREN, GRANDCHILDREN, PROSPECT_MANAGER, PROSPECTSTATUS, AMICUS, PROSPECTPOOL,
			  GENDER, MARITALSTATUS, SPOUSE_CONSTITUENTID, ETHNICITY, DISTINCTYEARGIVING, LATITUDE, LONGITUDE, 
			  PROSPECT_MANAGER_TEAM, PROSPECT_MANAGER_USERNAME, [PROSPECTMANAGERID]
	
	OPTION (OPTIMIZE FOR UNKNOWN)

