use EJDEVO;

SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
delete from EJ_PROSPECT_PIPELINE_STATUS;

insert into EJ_PROSPECT_PIPELINE_STATUS (
PROSPECTID
, PLANID
, NARRATIVE
, OPPORTUNITYID
, PLANTYPE
, SORT
, PROSPECTSTATUS
, NAME
, PLANNAME
, CITY
, STATE
, PROSPECTMANAGER
, PRIMARYMANAGER
, BUDGETDATE
, BUDGETAMOUNT
, ASKDATE
, ASKAMOUNT
, REVENUECOMMITTED
, CURRENT_GIVING
,[5 Year Capacity]
,[Affinity]
,[Estimated Wealth]
,[Inclination]

)
select 
PROSPECTID
, PLANID
, NARRATIVE
, OPPORTUNITYID
, PLANTYPE
, SORT
, PROSPECTSTATUS
, NAME
, PLANNAME
, CITY
, STATE
, PROSPECTMANAGER
, PRIMARYMANAGER
, BUDGETDATE
, BUDGETAMOUNT
, ASKDATE
, ASKAMOUNT
, REVENUECOMMITTED
, CURRENT_GIVING
,[5 Year Capacity]
,[Affinity]
,[Estimated Wealth]
,[Inclination]
FROM 
(

select
	*
from
(
select  distinct
	CONSTITUENT.CONSTITUENTID [PROSPECTID],
	PROSPECTPLAN.ID [PLANID],
	PROSPECTPLAN.NARRATIVE [NARRATIVE],
	OPPORTUNITIES.ID [OPPORTUNITYID],
	PROSPECTPLAN.TYPE as PLANTYPE,
 	CONSTITUENT.SORT_NAME [SORT],
	CONSTITUENT.PROSPECTSTATUS [PROSPECTSTATUS],
	CONSTITUENT.[NAME] as NAME,
	PROSPECTPLAN.NAME [PLANNAME],
	CONSTITUENT.[CITY] as CITY,
	CONSTITUENT.[STATE] as STATE,
	CONSTITUENT.PROSPECT_MANAGER as PROSPECTMANAGER,
	PRIMARY_MANAGER.[NAME] as PRIMARYMANAGER,
	OPPORTUNITIES.[EXPECTEDASKDATE] as BUDGETDATE,
	OPPORTUNITIES.[EXPECTEDASKAMOUNT] as BUDGETAMOUNT,
	OPPORTUNITIES.[ASKDATE] as ASKDATE,
	OPPORTUNITIES.[ASKAMOUNT] as ASKAMOUNT,
	OPPORTUNITIES.[REVENUECOMMITTED] as REVENUECOMMITTED,
	CONSTITUENT.ANNUAL_SUMMARY_CASH_YEAR_0 as CURRENT_GIVING,
	[5YEAR].[VALUE] as [5 Year Capacity],
	[AFFINITY].[VALUE] as [Affinity],
	[WEALTH].[VALUE] as [Estimated Wealth],
	[INCLINATION].[VALUE] as [Inclination]
from EJ_CONSTITUENT_HISTORY CONSTITUENT
inner join [dbo].[V_QUERY_PROSPECTPLAN] as PROSPECTPLAN on CONSTITUENT.[CONSTITUENTID] = PROSPECTPLAN.[PROSPECTID]
inner join [dbo].[V_QUERY_CONSTITUENT] as PRIMARY_MANAGER on PROSPECTPLAN.[PRIMARYMANAGERFUNDRAISERID] = PRIMARY_MANAGER.[ID]
left outer join [dbo].[V_QUERY_OPPORTUNITY] as OPPORTUNITIES on PROSPECTPLAN.[ID] = OPPORTUNITIES.[PROSPECTPLANID]
left outer join [dbo].[V_QUERY_ATTRIBUTEDCEFF2E9FDAB4674901120B7D8F75872] as [5YEAR] on [RESEARCH].[ID] = [5YEAR].[ID]
left outer join [dbo].[V_QUERY_ATTRIBUTE5357D4F4D90B4705B1E72D4FDD379F11] as [AFFINITY] on [RESEARCH].[ID] = [AFFINITY].[ID]
left outer join [dbo].[V_QUERY_ATTRIBUTED6169246286E4F48936E75C15FFCF562] as [WEALTH] on [RESEARCH].[ID] = [WEALTH].[ID]
left outer join [dbo].[V_QUERY_ATTRIBUTEC85D77A0E0C54C08AD316C31FCDB5B02] as [INCLINATION] on [RESEARCH].[ID] = [INCLINATION].[ID]
left outer join [dbo].[V_QUERY_ATTRIBUTE6920A0A601734A38A098EE001E5D02F0] as [RECENTRESEARCH] on [RESEARCH].ID = [RECENTRESEARCH].ID
where PROSPECTPLAN.HISTORICAL = 0
	 and CONSTITUENT.DECEASED = 0
	 and CONSTITUENT.INACTIVE = 0
) SUB

) SUB2

ORDER BY NAME, SORT
	
OPTION (OPTIMIZE FOR UNKNOWN)