SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

UPDATE EJ_PROSPECT_PIPELINE_STATUS
set LASTMOVE = SUB.LASTMOVE

from
(
select distinct
	PIPELINE.PROSPECTID,
	LAST_MOVE.LASTMOVE [LASTMOVE]
from
EJ_PROSPECT_PIPELINE_STATUS PIPELINE
left outer join (
	select
		SUB.CONSTITUENTID,
		SUB.SUBCATEGORY,
		SUB.DATE,
		SUB.OBJECTIVE
		from (
			select
				INTERACTION.CONSTITUENTID,
				convert(char(10), INTERACTION.DATE, 101) DATE,
				INTERACTIONSUBCATEGORY.NAME SUBCATEGORY,
				INTERACTION.OBJECTIVE,
				ROW_NUMBER() OVER (PARTITION BY INTERACTION.CONSTITUENTID
												ORDER BY INTERACTION.CONSTITUENTID,
											INTERACTION.DATE desc) AS ROWNUMBER
			from V_QUERY_INTERACTIONALL INTERACTION
			inner join INTERACTIONSUBCATEGORY on INTERACTION.INTERACTIONSUBCATEGORYID = INTERACTIONSUBCATEGORY.ID
			inner join INTERACTIONTYPECODE on INTERACTION.INTERACTIONTYPECODEID = INTERACTIONTYPECODE.ID
			where INTERACTION.DATE < getDate()
				and INTERACTION.COMPLETED = 1
			) SUB
	) LAST_MOVE on PIPELINE.PROSPECTID = LAST_MOVE.CONSTITUENTID
) SUB
where EJ_PROSPECT_PIPELINE_STATUS.PROSPECTID = SUB.PROSPECTID